name: poc
on:
  workflow_dispatch:
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: checkout
         uses: actions/checkout@v4
       - name: build
         run: |
            mvn clean package
   test:
     runs-on: ubuntu-latest
     steps:
       - name: testing
         run: |
            mvn test
