name: poc
on:
  workflow_dispatch:
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: checkout
         uses: actions/checkout@v4
       - name: setup
         uses: actions/setup-java@v4
         with: 
            distribution: 'temurin'
            version: '17'
       - name: build
         run: |
            mvn clean package
       - name: docker build
         run: |
            docker build -t samba1232/img1 .
       - name: pushing 
         run: |
            echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
            docker push samba1232/img1
   test:
     needs: build
     runs-on: ubuntu-latest
     steps:
       - name: checkout
         uses: actions/checkout@v4
       - name: setup
         uses: actions/setup-java@v4
       - name: testing
         run: |
            mvn test
   deploy:
    needs: test
    runs-on: ubuntu-latest
