name: poc
on:
  workflow_dispatch:
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: checkout
         uses: actions/checkout@v4
       - name: setup
         uses: actions/setup-java@v4
         with: 
            distribution: 'temurin'
            java-version: '17'
       - name: build
         run: |
            mvn clean package -X
       # - name: List WAR file (debug)
       #   run: |
       #    ls -lh web/target/
       - name: docker build
         run: |
            docker build -t samba1232/img1 .
       - name: pushing 
         run: |
            echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOKCER_USERNAME}}" --password-stdin
            docker push samba1232/img1
   test:
     needs: build
     runs-on: ubuntu-latest
     steps:
       - name: checkout
         uses: actions/checkout@v4
       - name: setup
         uses: actions/setup-java@v4
         with:
          distribution: 'temurin'
          java-version: 17
       - name: testing
         run: |
            mvn test
   deploy:
    needs: test
    runs-on: [aws-ec2]
    steps:
      - name: deploying into aws
        run: |
           docker pull samba1232/img1
           docker run --rm -p 8080:8080 samba1232/img1
