name: poc1
on:
  workflow_dispatch:
jobs:
    task1:
      runs-on: ubuntu-latest
      steps:
        - name: installing nginx
          run: |
            sudo apt update -y
            sudo apt-get install -y nginx
            sudo systemctl enable nginx
            sudo systemctl start nginx
        - name: accesing the webpage
          run: |
              curl http://localhost
    build:
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v3
        - name: installing maven
          run: |
             sudo apt update -y
             sudo apt-get install -y openjdk-17-jdk
             sudo apt install -y maven
             java -version
             mvn -v
        - name: buiding application using maven
          run: |
              mvn clean package
    test:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v3
        - name: testing
          run: |
            mvn test
    
            
           
           
