name: poc2

on:
  workflow_dispatch:

jobs:
  task1:
    runs-on: [ec2]
    steps:
      - name: Install Nginx
        run: |
          sudo apt update -y
          sudo apt install -y nginx
          sudo systemctl enable nginx
          sudo systemctl start nginx

      - name: Access Nginx default page
        run: curl http://16.176.148.239

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Java and Maven
        run: |
          sudo apt update -y
          sudo apt install -y openjdk-17-jdk maven
          java -version
          mvn -v

      - name: Build application using Maven
        run: mvn clean package

      - name: Upload WAR file
        uses: actions/upload-artifact@v4
        with:
          name: war-artifact
          path: web/target/time-tracker-web-*.war

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: mvn test

  pushing_artifactory:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: war-artifact
          path: web/target/

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t samba1232/img2 .
          docker push samba1232/img2

  deploying_on_aws:
    needs: pushing_artifactory
    runs-on: [ec2]
    steps:
      - name: Pull and run Docker image
        run: |
          docker pull samba1232/img2
          docker stop myapp || true
          docker rm myapp || true
          docker run -d --name myapp -p 8080:8080 samba1232/img2
