name: poc2

on:
  workflow_dispatch:

jobs:
  task1:
    runs-on: [ec2]
    steps:
      - name: Install Nginx
        run: |
          sudo apt update -y
          sudo apt install -y nginx
          sudo systemctl enable nginx
          sudo systemctl start nginx

      - name: Access Nginx default page
        run: curl http://16.176.148.239

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Java and Maven
        run: |
          sudo apt update -y
          sudo apt install -y openjdk-17-jdk maven
          java -version
          mvn -v

      - name: Build application using Maven
        run: mvn clean package

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: mvn test

  pushing_artifactory:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: |
          echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t samba1232/img2 .
          docker push samba1232/img2
  deploying_on_aws:
     runs-on: [ec2]
     steps:
       - name: deploying
         run: |
           docker pull samba1232/img2
        
